# Generated by Django 5.2.5 on 2025-08-08 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="featured_image",
            field=models.ImageField(
                blank=True, upload_to="blog/featured/", verbose_name="Featured Image"
            ),
        ),
        migrations.CreateModel(
            name="PostImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="blog/gallery/", verbose_name="Image"),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Caption"
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Alt Text"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Uploaded"),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="blog.post",
                        verbose_name="Post",
                    ),
                ),
            ],
            options={
                "verbose_name": "Post Image",
                "verbose_name_plural": "Post Images",
                "ordering": ["order", "uploaded_at"],
            },
        ),
    ]
